---
version: "3.9"

services:
  eclipse-tabnine:
    platform: linux/amd64
    image: wolkenschieber/eclipse-tabnine:latest
    restart: unless-stopped
    container_name: eclipse-tabnine
    shm_size: '1gb'
    environment:
      - PUID=501 
      - PGID=20
      - TZ=Europe/Berlin
      - ECLIPSE_DEBUG=0
      - ECLIPSE_RUN_AS_ROOT=1
    ports:
      - "3000:3000"
    networks:
      - eclipse-tabnine
    volumes:
      - ./config:/config

networks:
  eclipse-tabnine:
